require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.impatient"
-- require "user.colorscheme"
require "user.onedark"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.gitsigns"
require "user.lualine"
require "user.indentline"
require "user.autocommands"
require "user.fidget"
require "user.asciidoctor"
require "user.filetype"
require "user.markdown-preview"
vim.g.markdown_fenced_languages = {
  "mermaid=mermaid"
}
