palette = 'foo'

[palettes.foo]
black = '#11111b'
red = '#f38ba8'
green = '#a6e3a1'
blue = '#89b4fa'
yellow = '#f9e2af'
purple = '#cba6f7'
cyan = '#89dceb'
white = '#cdd6f4'
base = '#1e1e2e'
bitcoin = '#fab387'

[username]
style_user = "bold purple"
style_root = "bold red"
format = "[$user]($style)"
disabled = true
show_always = false

[hostname]
ssh_only = true
format = "@[$hostname](bold cyan) [$ssh_symbol](bold yellow)"
trim_at = "."
disabled = false

[directory]
style = 'bold blue'
read_only_style = 'bold red'
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[character]
success_symbol = '[\$](bitcoin)'
error_symbol = '[✗](bold red)'

[python]
format = ': [${symbol}(${version} )(\($virtualenv\) )]($style)'
version_format = 'v${raw}'
pyenv_version_name = true

[c]
detect_extensions = [ 'c', 'cpp', 'h']
detect_files = [ 'libbitcoinconsensus.pc.in' ]
commands = [ [ 'clang', '--version' ] ]
version_format = 'v${raw}'
format = ': [$symbol($version(-$name) )]($style)'

[gcloud]
disabled = true
