[username]
#style_user = "white bold"
#style_root = "black bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "@[$hostname](bold green) [$ssh_symbol](bold blue)"
trim_at = ".companyname.com"
disabled = false

[directory]
format="in [$path]($style)[$read_only]($read_only_style) "
#truncation_length = 8
#truncation_symbol = "…/"
